name: ivedras_env
channels:
  - snowflake
dependencies:
  - streamlit=1.44.0
  - pandas
  - numpy
  - plotly
  - folium
  - streamlit-folium
  - pydeck
  - spacy
  - scikit-learn
  - sentencepiece
  - python-levenshtein
  - rapidfuzz
  - joblib
  - thinc 